#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 25 13:00:49 2022

@author: alexs2
"""

from scipy import stats
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import statistics
from scipy.stats import norm

"""
SECCION DEL VIDEOJUEGO
"""
#generar valores
vg_first_test = [38,37,42,53,44,44,55,37,44,39,46,47,45,46,42,40]
arr_firstvg = np.asarray(vg_first_test)

vg_second_test = [45,40,42,46,48,44,51,37,44,52,44,50,42,48,53,41]
arr_secondvg = np.asarray(vg_second_test)

t_value,p_value=stats.ttest_rel(vg_second_test,vg_first_test)

one_tailed_p_value=float("{:.6f}".format(p_value/2)) 

print("16 estudiantes fueron evaluados mediante el S-STAI antes y despues de utilizar un videojuego para la ansiedad")
print("¿el videojuego les sirvió para la ansiedad?")

print("h0: los estudiantes no disminuyeron su ansiedad gracias al software (d=0)")
print("h1: los estudiantes disminuyeron su ansiedad gracias al software (d<0)")


print('El test estadistico es %f'%float("{:.6f}".format(t_value)))

print('el p-value para una prueba one-tailed es %f'%one_tailed_p_value)

alpha = 0.1

if one_tailed_p_value<=alpha:

    print('Conclusion','n','Dado que el p-value(=%f)'%one_tailed_p_value,'<','alpha(=%.2f)'%alpha,'''Se rechaza la hipotesis nula H0. 

Se concluye que los estudiantes disminuyeron su ansiedad gracias al videojuego. i.e., d = 0 a un nivel de significancia de %.2f '''%alpha)

else:

    print('Conclusion','n','Dado que el p-value(=%f)'%one_tailed_p_value,'>','alpha(=%.2f)'%alpha,'''No se rechaza la hipotesis H0. 

Se concluye que los estudiantes no disminuyeron su ansiedad gracias al videojuego. i.e., d = 0 a un nivel de significancia de %.2f '''%alpha)


print('\n')



"""
SECCION DE CONTROL
"""

control_first_test = [33,40,39,51,39,39,40,45,43,36,47,43,45,48,0,0]
arr_firstcontrol = np.asarray(control_first_test)

control_second_test = [31,47,36,48,41,44,43,46,41,42,39,49,49,52,0,0]
arr_secondcontrol = np.asarray(control_second_test)


t_value,p_value=stats.ttest_rel(control_second_test,control_first_test, alternative='less')

one_tailed_p_value=float("{:.6f}".format(p_value/2)) 

print("14 estudiantes fueron evaluados mediante el S-STAI antes y despues de utilizar audio para la ansiedad")
print("¿el audio les sirvió para la ansiedad?")

print("h0: los estudiantes no disminuyeron su ansiedad gracias al software (d=0)")
print("h1: los estudiantes disminuyeron su ansiedad gracias al software (d<0)")


print('El test estadistico es %f'%float("{:.6f}".format(t_value)))

print('el p-value para una prueba one-tailed es %f'%one_tailed_p_value)

alpha = 0.1

if one_tailed_p_value<=alpha:

    print('Conclusion','n','Dado que el p-value(=%f)'%one_tailed_p_value,'<','alpha(=%.2f)'%alpha,'''Se rechaza la hipotesis nula H0. 

Se concluye que los estudiantes disminuyeron su ansiedad gracias al audio. i.e., d = 0 a un nivel de significancia de %.2f '''%alpha)

else:

    print('Conclusion','n','Dado que el p-value(=%f)'%one_tailed_p_value,'>','alpha(=%.2f)'%alpha,'''No se rechaza la hipotesis H0. 

Se concluye que los estudiantes no disminuyeron su ansiedad gracias al audio. i.e., d = 0 a un nivel de significancia de %.2f '''%alpha)

print("\n")

"""
DIFERENCIA ENTRE AMBOS
"""
diff_vg = arr_secondvg - arr_firstvg

diff_control = arr_secondcontrol - arr_firstcontrol

t_value, p_value = stats.ttest_ind(diff_vg, diff_control, equal_var=False)
one_tailed_p_value = float("{:.6f}".format(p_value/2))

print("30 estudiantes en total participaron en un experimento donde se utilizaron dos vías orientadas a la reduccion de ansiedad")
print("una de ellas fue jugar a un videojuego, y la otra fue escuchar musica")
print("¿cual de las vias funcionó más?")

print("h0: el videojuego funcionó mas que el audio")
print("h1: el audio funcionó mas que el videojuego")

print('El test estadistico es %f'%float("{:.6f}".format(t_value)))

print('el p-value para una prueba one-tailed es %f'%one_tailed_p_value)

print("\n")

alpha = 0.1

if one_tailed_p_value<=alpha:

    print('Conclusion','n','Dado que el p-value(=%f)'%one_tailed_p_value,'<','alpha(=%.2f)'%alpha,'''Se rechaza la hipotesis nula H0. 

Se concluye que el videojuego funcionó mas que el audio a un nivel de significancia de %.2f '''%alpha)

else:

    print('Conclusion','n','Dado que el p-value(=%f)'%one_tailed_p_value,'>','alpha(=%.2f)'%alpha,'''No se rechaza la hipotesis H0. 

Se concluye que el audio funcionó mas que el videojuego a un nivel de significancia de %.2f '''%alpha)


